language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t bondbatif/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bondbatif/docker-react npm run test
